### ISSUE TITLE
Connecting R to Tableau

### ISSUE THREAD

**Issue by loisjung** [ridhimab04/Connecting-R-To-Tableau#1]
I am having an issue connecting R to Tableau. Could you please help how I can resolve this?

> install.packages("Rserve")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://mirrors.nics.utk.edu/cran/bin/macosx/contrib/4.0/Rserve_1.7-3.1.tgz'
Content type 'application/x-gzip' length 320856 bytes (313 KB)
==================================================
downloaded 313 KB

The downloaded binary packages are in
	/var/folders/sd/6b0mc5852pxd5z5qm743qh500000gn/T//Rtmp6JFS2u/downloaded_packages
> library(Rserve)
> Rserve()
Starting Rserve:
 /Library/Frameworks/R.framework/Resources/bin/R CMD /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rserve/libs//Rserve 

Fatal error: you must specify '--save', '--no-save' or '--vanilla'
> Rserve(args="--no-save")
Starting Rserve:
 /Library/Frameworks/R.framework/Resources/bin/R CMD /Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rserve/libs//Rserve --no-save 

R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

Rserv started in daemon mode.
##> SOCK_ERROR: bind error #48(address already in use)

**Comment by ridhimab04** [comment]
Hi @loisjung , seems like the server is already running, which is why you get "SOCK_ERROR: bind error #48(address already in use)". Try to stop and run the server the again.
